export const groupsData = [
  {
    id: "A",
    teams: [
      {
        country: "Qatar",
        code: "QA",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        
      },
      {
        country: "Ecuador",
        code: "EC",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        
      },
      {
        country: "Senegal ",
        code: "SN",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "Netherlands ",
        code: "NL",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
    ],
  },
  {
    id: "B",
    teams: [
      {
        country: "England",
        code: "GB-ENG",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "Iran",
        code: "IR",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "United States",
        code: "US",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "Wales",
        code: "GB-WLS",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
    ],
  },
  {
    id: "C",
    teams: [
      {
        country: "Argentina",
        code: "AR",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "Saudi Arabia",
        code: "SA",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "Mexico",
        code: "MX",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "Poland ",
        code: "PL",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
    ],
  },
  {
    id: "D",
    teams: [
      {
        country: "France",
        code: "FR",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "Australia",
        code: "AU",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "Denmark",
        code: "DK",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "Tunisia",
        code: "TN",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
    ],
  },
  {
    id: "E",
    teams: [
      {
        country: "Spain",
        code: "ES",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "Costa Rica",
        code: "CR",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "Germany",
        code: "DE",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "Japan",
        code: "JP",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
    ],
  },
  {
    id: "F",
    teams: [
      {
        country: "Belgium",
        code: "BE",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "Canada",
        code: "CA",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "Morocco",
        code: "MA",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "Croatia",
        code: "HR",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
    ],
  },
  {
    id: "G",
    teams: [
      {
        country: "Brazil",
        code: "BR",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "Serbia",
        code: "RS",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "Switzerland",
        code: "CH",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "Cameroon",
        code: "CM",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
    ],
  },
  {
    id: "H",
    teams: [
      {
        country: "Portugal",
        code: "PT",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "Ghana",
        code: "GH",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "Uruguay",
        code: "UY",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
      {
        country: "South Korea",
        code: "KR",
        gamesPlayed: 0,
        points: 0,
        win: 0,
        tie: 0,
        loss: 0,
        goalsFor: 0,
        goalsAgainst: 0,
      },
    ],
  },
];

export const matches = [
  {
    matchNumber: 1,
    roundNumber: 1,
    dateUtc: "2022-11-20 16:00:00Z",
    location: "Al Bayt Stadium",
    homeTeam: { country: "Qatar", code: "QA" },
    awayTeam: { country: "Ecuador", code: "EC" },
    group: "group A",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 3,
    roundNumber: 1,
    dateUtc: "2022-11-21 13:00:00Z",
    location: "Khalifa International Stadium",
    homeTeam: { country: "England", code: "GB-ENG" },
    awayTeam: { country: "Iran", code: "IR" },
    group: "group B",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 2,
    roundNumber: 1,
    dateUtc: "2022-11-21 16:00:00Z",
    location: "Al Thumama Stadium",
    homeTeam: { country: "Senegal", code: "SN" },
    awayTeam: { country: "Netherlands", code: "NL" },
    group: "group A",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 4,
    roundNumber: 1,
    dateUtc: "2022-11-21 19:00:00Z",
    location: "Ahmad Bin Ali Stadium",
    homeTeam: { country: "United States", code: "US" },
    awayTeam: { country: "Wales", code: "GB-WLS" },
    group: "group B",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 8,
    roundNumber: 1,
    dateUtc: "2022-11-22 10:00:00Z",
    location: "Lusail Stadium",
    homeTeam: { country: "Argentina", code: "AR" },
    awayTeam: { country: "Saudi Arabia", code: "SA" },
    group: "group C",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 6,
    roundNumber: 1,
    dateUtc: "2022-11-22 13:00:00Z",
    location: "Education City Stadium",
    homeTeam: { country: "Denmark", code: "DK" },
    awayTeam: { country: "Tunisia", code: "TN" },
    group: "group D",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 7,
    roundNumber: 1,
    dateUtc: "2022-11-22 16:00:00Z",
    location: "Stadium 974",
    homeTeam: { country: "Mexico", code: "MX" },
    awayTeam: { country: "Poland", code: "PL" },
    group: "group C",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 5,
    roundNumber: 1,
    dateUtc: "2022-11-22 19:00:00Z",
    location: "Al Janoub Stadium",
    homeTeam: { country: "France", code: "FR" },
    awayTeam: { country: "Australia", code: "AU" },
    group: "group D",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 12,
    roundNumber: 1,
    dateUtc: "2022-11-23 10:00:00Z",
    location: "Al Bayt Stadium",
    homeTeam: { country: "Morocco", code: "MA" },
    awayTeam: { country: "Croatia", code: "HR" },
    group: "group F",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 11,
    roundNumber: 1,
    dateUtc: "2022-11-23 13:00:00Z",
    location: "Khalifa International Stadium",
    homeTeam: "",
    awayTeam: "Japan",
    homeTeam: { country: "Germany", code: "DE" },
    awayTeam: { country: "Croatia", code: "HR" },
    group: "group E",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 10,
    roundNumber: 1,
    dateUtc: "2022-11-23 16:00:00Z",
    location: "Al Thumama Stadium",
    homeTeam: { country: "Spain", code: "ES" },
    awayTeam: { country: "Costa Rica", code: "CR" },
    group: "group E",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 9,
    roundNumber: 1,
    dateUtc: "2022-11-23 19:00:00Z",
    location: "Ahmad Bin Ali Stadium",
    homeTeam: { country: "Belgium", code: "BE" },
    awayTeam: { country: "Canada", code: "CA" },
    group: "group F",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 13,
    roundNumber: 1,
    dateUtc: "2022-11-24 10:00:00Z",
    location: "Al Janoub Stadium",
    homeTeam: { country: "Switzerland", code: "CH" },
    awayTeam: { country: "Cameroon", code: "CM" },
    group: "group G",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 14,
    roundNumber: 1,
    dateUtc: "2022-11-24 13:00:00Z",
    location: "Education City Stadium",
    homeTeam: { country: "Uruguay", code: "UY" },
    awayTeam: { country: "Korea Republic", code: "KR" },
    group: "group H",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 15,
    roundNumber: 1,
    dateUtc: "2022-11-24 16:00:00Z",
    location: "Stadium 974",
    homeTeam: { country: "Portugal", code: "PT" },
    awayTeam: { country: "Ghana", code: "GH" },
    group: "group H",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 16,
    roundNumber: 1,
    dateUtc: "2022-11-24 19:00:00Z",
    location: "Lusail Stadium",
    homeTeam: "",
    awayTeam: "",
    homeTeam: { country: "Brazil", code: "BR" },
    awayTeam: { country: "Serbia", code: "RS" },
    group: "group G",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 17,
    roundNumber: 2,
    dateUtc: "2022-11-25 10:00:00Z",
    location: "Ahmad Bin Ali Stadium",
    homeTeam: { country: "Wales", code: "GB-WLS" },
    awayTeam: { country: "Iran", code: "IR" },
    group: "group B",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 18,
    roundNumber: 2,
    dateUtc: "2022-11-25 13:00:00Z",
    location: "Al Thumama Stadium",
    homeTeam: { country: "Qatar", code: "QA" },
    awayTeam: { country: "Senegal", code: "SN" },
    group: "group A",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 19,
    roundNumber: 2,
    dateUtc: "2022-11-25 16:00:00Z",
    location: "Khalifa International Stadium",
    homeTeam: { country: "Netherlands", code: "NL" },
    awayTeam: { country: "Ecuador", code: "EC" },
    group: "group A",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 20,
    roundNumber: 2,
    dateUtc: "2022-11-25 19:00:00Z",
    location: "Al Bayt Stadium",
    homeTeam: { country: "England", code: "GB-ENG" },
    awayTeam: { country: "United States", code: "US" },
    group: "group B",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 21,
    roundNumber: 2,
    dateUtc: "2022-11-26 10:00:00Z",
    location: "Al Janoub Stadium",
    homeTeam: { country: "Tunisia", code: "TN" },
    awayTeam: { country: "Australia", code: "AU" },
    group: "group D",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 22,
    roundNumber: 2,
    dateUtc: "2022-11-26 13:00:00Z",
    location: "Education City Stadium",
    homeTeam: { country: "Poland", code: "PL" },
    awayTeam: { country: "Saudi Arabia", code: "SA" },
    group: "group C",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 23,
    roundNumber: 2,
    dateUtc: "2022-11-26 16:00:00Z",
    location: "Stadium 974",
    homeTeam: { country: "France", code: "FR" },
    awayTeam: { country: "Denmark", code: "DK" },
    group: "group D",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 24,
    roundNumber: 2,
    dateUtc: "2022-11-26 19:00:00Z",
    location: "Lusail Stadium",
    homeTeam: { country: "Argentina", code: "AR" },
    awayTeam: { country: "Mexico", code: "MX" },
    group: "group C",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 25,
    roundNumber: 2,
    dateUtc: "2022-11-27 10:00:00Z",
    location: "Ahmad Bin Ali Stadium",
    homeTeam: { country: "Japan", code: "JP" },
    awayTeam: { country: "Costa Rica", code: "CR" },
    group: "group E",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 26,
    roundNumber: 2,
    dateUtc: "2022-11-27 13:00:00Z",
    location: "Al Thumama Stadium",
    homeTeam: { country: "Belgium", code: "BE" },
    awayTeam: { country: "Morocco", code: "MA" },
    group: "group F",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 27,
    roundNumber: 2,
    dateUtc: "2022-11-27 16:00:00Z",
    location: "Khalifa International Stadium",
    homeTeam: { country: "Croatia", code: "HR" },
    awayTeam: { country: "Canada", code: "CA" },
    group: "group F",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 28,
    roundNumber: 2,
    dateUtc: "2022-11-27 19:00:00Z",
    location: "Al Bayt Stadium",
    homeTeam: { country: "Spain", code: "ES" },
    awayTeam: { country: "Germany", code: "DE" },
    group: "group E",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 29,
    roundNumber: 2,
    dateUtc: "2022-11-28 10:00:00Z",
    location: "Al Janoub Stadium",
    homeTeam: { country: "Cameroon", code: "CM" },
    awayTeam: { country: "Serbia", code: "RS" },
    group: "group G",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 30,
    roundNumber: 2,
    dateUtc: "2022-11-28 13:00:00Z",
    location: "Education City Stadium",
    homeTeam: { country: "Korea Republic", code: "KR" },
    awayTeam: { country: "Ghana", code: "GH" },
    group: "group H",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 31,
    roundNumber: 2,
    dateUtc: "2022-11-28 16:00:00Z",
    location: "Stadium 974",
    homeTeam: { country: "Brazil", code: "BR" },
    awayTeam: { country: "Switzerland", code: "CH" },
    group: "group G",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 32,
    roundNumber: 2,
    dateUtc: "2022-11-28 19:00:00Z",
    location: "Lusail Stadium",
    homeTeam: { country: "Portugal", code: "PT" },
    awayTeam: { country: "Uruguay", code: "UY" },
    group: "group H",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 35,
    roundNumber: 3,
    dateUtc: "2022-11-29 15:00:00Z",
    location: "Khalifa International Stadium",
    homeTeam: { country: "Ecuador", code: "EC" },
    awayTeam: { country: "Senegal", code: "SN" },
    group: "group A",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 36,
    roundNumber: 3,
    dateUtc: "2022-11-29 15:00:00Z",
    location: "Al Bayt Stadium",
    homeTeam: { country: "Netherlands", code: "NL" },
    awayTeam: { country: "Qatar", code: "QA" },
    group: "group A",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 33,
    roundNumber: 3,
    dateUtc: "2022-11-29 19:00:00Z",
    location: "Ahmad Bin Ali Stadium",
    homeTeam: { country: "Wales", code: "GB-WLS" },
    awayTeam: { country: "England", code: "GB-ENG" },
    group: "group B",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 34,
    roundNumber: 3,
    dateUtc: "2022-11-29 19:00:00Z",
    location: "Al Thumama Stadium",
    homeTeam: { country: "Iran", code: "IR" },
    awayTeam: { country: "United States", code: "US" },
    group: "group B",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 37,
    roundNumber: 3,
    dateUtc: "2022-11-30 15:00:00Z",
    location: "Al Janoub Stadium",
    homeTeam: { country: "Australia", code: "AU" },
    awayTeam: { country: "Denmark", code: "DK" },
    group: "group D",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 38,
    roundNumber: 3,
    dateUtc: "2022-11-30 15:00:00Z",
    location: "Education City Stadium",
    homeTeam: { country: "Tunisia", code: "TN" },
    awayTeam: { country: "France", code: "FR" },
    group: "group D",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 39,
    roundNumber: 3,
    dateUtc: "2022-11-30 19:00:00Z",
    location: "Stadium 974",
    homeTeam: { country: "Poland", code: "PL" },
    awayTeam: { country: "Argentina", code: "AR" },
    group: "group C",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 40,
    roundNumber: 3,
    dateUtc: "2022-11-30 19:00:00Z",
    location: "Lusail Stadium",
    homeTeam: { country: "Saudi Arabia", code: "SA" },
    awayTeam: { country: "Mexico", code: "MX" },
    group: "group C",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 41,
    roundNumber: 3,
    dateUtc: "2022-12-01 15:00:00Z",
    location: "Ahmad Bin Ali Stadium",
    homeTeam: { country: "Croatia", code: "HR" },
    awayTeam: { country: "Belgium", code: "BE" },
    group: "group F",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 42,
    roundNumber: 3,
    dateUtc: "2022-12-01 15:00:00Z",
    location: "Al Thumama Stadium",
    homeTeam: { country: "Canada", code: "CA" },
    awayTeam: { country: "Morocco", code: "MA" },
    group: "group F",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 43,
    roundNumber: 3,
    dateUtc: "2022-12-01 19:00:00Z",
    location: "Khalifa International Stadium",
    homeTeam: { country: "Japan", code: "JP" },
    awayTeam: { country: "Spain", code: "ES" },
    group: "group E",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 44,
    roundNumber: 3,
    dateUtc: "2022-12-01 19:00:00Z",
    location: "Al Bayt Stadium",
    homeTeam: { country: "Costa Rica", code: "CR" },
    awayTeam: { country: "Germany", code: "DE" },
    group: "group E",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 45,
    roundNumber: 3,
    dateUtc: "2022-12-02 15:00:00Z",
    location: "Al Janoub Stadium",
    homeTeam: { country: "Ghana", code: "GH" },
    awayTeam: { country: "Uruguay", code: "UY" },
    group: "group H",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 46,
    roundNumber: 3,
    dateUtc: "2022-12-02 15:00:00Z",
    location: "Education City Stadium",
    homeTeam: { country: "Korea Republic", code: "KR" },
    awayTeam: { country: "Portugal", code: "PT" },
    group: "group H",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 47,
    roundNumber: 3,
    dateUtc: "2022-12-02 19:00:00Z",
    location: "Stadium 974",
    homeTeam: { country: "Serbia", code: "RS" },
    awayTeam: { country: "Switzerland", code: "CH" },
    group: "group G",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  {
    matchNumber: 48,
    roundNumber: 3,
    dateUtc: "2022-12-02 19:00:00Z",
    location: "Lusail Stadium",
    homeTeam: { country: "Cameroon", code: "CM" },
    awayTeam: { country: "Brazil", code: "BR" },
    group: "group G",
    homeTeamScore: null,
    awayTeamScore: null,
  },
  // {
  //   matchNumber: 49,
  //   roundNumber: 4,
  //   dateUtc: "2022-12-03 15:00:00Z",
  //   location: "TBA",
  //   homeTeam: "1A",
  //   awayTeam: "2B",
  //   group: null,
  //   homeTeamScore: null,
  //   awayTeamScore: null,
  // },
  // {
  //   matchNumber: 50,
  //   roundNumber: 4,
  //   dateUtc: "2022-12-03 19:00:00Z",
  //   location: "TBA",
  //   homeTeam: "1C",
  //   awayTeam: "2D",
  //   group: null,
  //   homeTeamScore: null,
  //   awayTeamScore: null,
  // },
  // {
  //   matchNumber: 52,
  //   roundNumber: 4,
  //   dateUtc: "2022-12-04 15:00:00Z",
  //   location: "TBA",
  //   homeTeam: "1D",
  //   awayTeam: "2C",
  //   group: null,
  //   homeTeamScore: null,
  //   awayTeamScore: null,
  // },
  // {
  //   matchNumber: 51,
  //   roundNumber: 4,
  //   dateUtc: "2022-12-04 19:00:00Z",
  //   location: "TBA",
  //   homeTeam: "1B",
  //   awayTeam: "2A",
  //   group: null,
  //   homeTeamScore: null,
  //   awayTeamScore: null,
  // },
  // {
  //   matchNumber: 53,
  //   roundNumber: 4,
  //   dateUtc: "2022-12-05 15:00:00Z",
  //   location: "TBA",
  //   homeTeam: "1E",
  //   awayTeam: "2F",
  //   group: null,
  //   homeTeamScore: null,
  //   awayTeamScore: null,
  // },
  // {
  //   matchNumber: 54,
  //   roundNumber: 4,
  //   dateUtc: "2022-12-05 19:00:00Z",
  //   location: "TBA",
  //   homeTeam: "1G",
  //   awayTeam: "2H",
  //   group: null,
  //   homeTeamScore: null,
  //   awayTeamScore: null,
  // },
  // {
  //   matchNumber: 55,
  //   roundNumber: 4,
  //   dateUtc: "2022-12-06 15:00:00Z",
  //   location: "TBA",
  //   homeTeam: "1F",
  //   awayTeam: "2E",
  //   group: null,
  //   homeTeamScore: null,
  //   awayTeamScore: null,
  // },
  // {
  //   matchNumber: 56,
  //   roundNumber: 4,
  //   dateUtc: "2022-12-06 19:00:00Z",
  //   location: "TBA",
  //   homeTeam: "1H",
  //   awayTeam: "2G",
  //   group: null,
  //   homeTeamScore: null,
  //   awayTeamScore: null,
  // },
  // {
  //   matchNumber: 58,
  //   roundNumber: 5,
  //   dateUtc: "2022-12-09 15:00:00Z",
  //   location: "TBA",
  //   homeTeam: "To be announced",
  //   awayTeam: "To be announced",
  //   group: null,
  //   homeTeamScore: null,
  //   awayTeamScore: null,
  // },
  // {
  //   matchNumber: 57,
  //   roundNumber: 5,
  //   dateUtc: "2022-12-09 19:00:00Z",
  //   location: "TBA",
  //   homeTeam: "To be announced",
  //   awayTeam: "To be announced",
  //   group: null,
  //   homeTeamScore: null,
  //   awayTeamScore: null,
  // },
  // {
  //   matchNumber: 60,
  //   roundNumber: 5,
  //   dateUtc: "2022-12-10 15:00:00Z",
  //   location: "TBA",
  //   homeTeam: "To be announced",
  //   awayTeam: "To be announced",
  //   group: null,
  //   homeTeamScore: null,
  //   awayTeamScore: null,
  // },
  // {
  //   matchNumber: 59,
  //   roundNumber: 5,
  //   dateUtc: "2022-12-10 19:00:00Z",
  //   location: "TBA",
  //   homeTeam: "To be announced",
  //   awayTeam: "To be announced",
  //   group: null,
  //   homeTeamScore: null,
  //   awayTeamScore: null,
  // },
  // {
  //   matchNumber: 61,
  //   roundNumber: 6,
  //   dateUtc: "2022-12-13 19:00:00Z",
  //   location: "TBA",
  //   homeTeam: "To be announced",
  //   awayTeam: "To be announced",
  //   group: null,
  //   homeTeamScore: null,
  //   awayTeamScore: null,
  // },
  // {
  //   matchNumber: 62,
  //   roundNumber: 6,
  //   dateUtc: "2022-12-14 19:00:00Z",
  //   location: "TBA",
  //   homeTeam: "To be announced",
  //   awayTeam: "To be announced",
  //   group: null,
  //   homeTeamScore: null,
  //   awayTeamScore: null,
  // },
  // {
  //   matchNumber: 63,
  //   roundNumber: 7,
  //   dateUtc: "2022-12-17 15:00:00Z",
  //   location: "TBA",
  //   homeTeam: "To be announced",
  //   awayTeam: "To be announced",
  //   group: null,
  //   homeTeamScore: null,
  //   awayTeamScore: null,
  // },
  // {
  //   matchNumber: 64,
  //   roundNumber: 7,
  //   dateUtc: "2022-12-18 15:00:00Z",
  //   location: "TBA",
  //   homeTeam: "To be announced",
  //   awayTeam: "To be announced",
  //   group: null,
  //   homeTeamScore: null,
  //   awayTeamScore: null,
  // },
];
